---

- name: create /opt/intrexx/solr
  file: path=/opt/intrexx/solr state=directory
  ignore_errors: yes
- name: remove /opt/intrexx/solr
  file: path=/opt/intrexx/solr state=absent
  ignore_errors: yes
- name: symbollink /opt/intrexx/solr -> {{ ix_shared_folder }}/solr
  file: path=/opt/intrexx/solr
        src="{{ ix_shared_folder }}/solr"
        state=link
        force=yes
