---

- name: remove /opt/intrexx/solr/server/solr
  file: path=/opt/intrexx/solr/server/solr state=absent
- name: symbollink /opt/intrexx/solr/server/solr -> {{ ix_shared_folder }}/solr
  file: path=/opt/intrexx/solr/server/solr
        src="{{ ix_shared_folder }}/solr"
        state=link
        force=yes