---
# set up nfs share
- name: install nfs-common
  apt: name=nfs-common state=present
- name: install rpcbind
  apt: name=rpcbind state=present
- name: Ensure NFS volumes is mounted.
  mount: name="{{ ix_shared_folder }}" src="{{ ix_nfs_share }}" fstype=nfs4 state=mounted