---
# partition disks
- name: Azure - partition disk for shared folder
  parted:
    device: /dev/sdc
    number: 1
    state: present
  when: ix_cloud_provider == "azure"

- name: Azure - Create a ext4 filesystem on /dev/sdc1
  filesystem:
    fstype: ext4
    dev: /dev/sdc1
  when: ix_cloud_provider == "azure"

- name: Azure - Mount device
  mount:
    path: /share
    src: /dev/sdc1
    fstype: ext4
    state: mounted
  when: ix_cloud_provider == "azure"

- name: AWS - partition disk for shared folder
  parted:
    device: /dev/xvdb
    number: 1
    state: present
  when: ix_cloud_provider == "aws" and ix_filesystem_type == "nfs"

- name: AWS - Create a ext4 filesystem on /dev/xvdb1
  filesystem:
    fstype: ext4
    dev: /dev/xvdb1
  when: ix_cloud_provider == "aws" and ix_filesystem_type == "nfs"

- name: AWS - Mount device
  mount:
    path: /share
    src: /dev/xvdb1
    fstype: ext4
    state: mounted
  when: ix_cloud_provider == "aws" and ix_filesystem_type == "nfs"
