---
# prepare setup
- name: Download Intrexx setup
  get_url:
    url: "https://download.unitedplanet.com/intrexx/90500/{{ ix_setup_filename }}"
    dest: "{{ ix_remote_home }}/{{ ix_setup_filename }}"
#- name: copy setup
#  copy: src=files/{{ ix_setup_filename }} dest={{ ix_remote_home }}/{{ ix_setup_filename }} force=no    
- name: copy services setup cfg
  template: src=files/configuration.properties.j2 dest="{{ ix_remote_home }}/configuration.properties" owner=root group=root mode=0644
  when: "'appserver_services' in group_names"
- name: copy portal setup cfg
  template: src=files/configuration_portal.properties.j2 dest="{{ ix_remote_home }}/configuration.properties" owner=root group=root mode=0644
  when: "'appserver_portal' in group_names"  
- name: untar setup
  command: tar xvfz {{ ix_setup_filename }}
  args:
    chdir: "{{ ix_remote_home }}"
    creates: "{{ ix_remote_home }}/{{ ix_setup_folder }}/setup.sh"
#- name: unzip setup
#  command: /usr/bin/7z x {{ ix_setup_filename }}
#  args:
#    chdir: "{{ ix_remote_home }}"
#    creates: "{{ ix_remote_home }}/{{ ix_setup_folder }}/setup.sh"    
- name: chmod setup
  file:
    path: "{{ ix_remote_home }}/{{ ix_setup_folder }}/setup.sh"
    mode: 0777
  ignore_errors: true
- name: chmod java
  file:
    path: "{{ ix_remote_home }}/{{ ix_setup_folder }}/java/packaged/linux/amd64/bin/java"
    mode: 0777
  ignore_errors: true

# install Intrexx
- name: install intrexx
  command: "{{ ix_remote_home }}/{{ ix_setup_folder }}/setup.sh -t --configFile={{ ix_remote_home }}/configuration.properties"
  args:
    creates: /opt/intrexx/bin/linux/portal.sh
