---
# This Playbook would deploy the whole SERVICES app server

- hosts: appserver_services
  vars_files:
    - ./vars.yml
  tasks:
  - name: Create directory structure
    win_file:
      path: C:\install
      state: directory

  - name: copy 7zip
    win_copy:
      src: files/7z1700-x64.msi
      dest: C:\install\7z1700-x64.msi

  - name: copy install.cmd for 7zip
    win_copy:
      src: files/install.cmd
      dest: C:\install\install.cmd

  - name: install 7zip
    args:
      creates: 'C:\Program Files\7-Zip'
      chdir: C:\install\
    win_command: C:\install\install.cmd
      
  - name: copy setup
    win_copy: 
      src: files/professional.zip 
      dest: C:\install\professional.zip
    args:
      creates: C:\install\professional.zip

  - name: copy setup cfg
    win_template: 
      src: files/configuration.j2
      dest: C:\install\configuration.properties

  - name: update portal config
    win_template: 
      src: files/portal_config.j2 
      dest: C:\install\portal_config.xml

  - name: unzip intrexx
    win_command: '"C:\Program Files\7-Zip\7z.exe" x C:\install\professional.zip -oC:\install'
    args:
      creates: C:\install\professional
      
  - name: Disable all firewalls
    win_firewall:
      state: disabled
      profiles:
      - Domain
      - Public
      - Private
    tags: disable_firewall

  - name: install intrexx
    win_command: C:\install\professional\setup.bat -t --configFile=C:\install\configuration.properties
    args:
      creates: C:\intrexx\bin\windows\portal.bat

  - name: install Portal
    win_command: C:\intrexx\bin\windows\buildportal.bat -t --configFile=C:\install\portal_config.xml
    args:
      creates: C:\share\{{ ix_portal_name }}\internal\cfg\portal.wcf
    
  - name: copy logon script 
    win_template: src=files/LogonServices.j2 dest=C:\install\LogonServices.ps1

  - name: enable logon
    win_shell: C:\install\LogonServices.ps1 "{{ aws_services_hostname }}\\{{ aws_username }}"
   
  - name: stop Portal
    win_service:
      name: upixp_{{ ix_portal_name }}
      state: stopped
      start_mode: auto
      username: "{{ aws_username }}"
      password: "{{ aws_services_pw }}"

  - name: Move cfg folder
    win_command: cmd /c move C:\intrexx\cfg C:\share\
    args:
      creates: C:\share\cfg\initial.cfg

  - name: mount cfg
    win_command: cmd /c mklink /D C:\intrexx\cfg C:\share\cfg
    args:
      creates: C:\intrexx\cfg\initial.cfg
      
  - name: share Portal
    win_share:
      name: share
      path: C:\share
      list: 'yes'
      full: Everyone

  - name: start Solr Service automatic
    win_service:
      name: upixsolr
      state: restarted
      start_mode: auto

  - name: start Portal Service 
    win_service:
      name: upixp_{{ ix_portal_name }}
      state: started
      start_mode: auto
      username: "{{ aws_username }}"
      password: "{{ aws_services_pw }}"

  - name: stop Supervisor service
    win_service:
      name: upixsupervisor
      state: stopped
      start_mode: manual
      username: "{{ aws_username }}"
      password: "{{ aws_services_pw }}"
