kind: Service
apiVersion: v1
metadata:
  name: ixcloudservice
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 1337
  selector:
    app: ixcloudapp