apiVersion: apps/v1
kind: Deployment
metadata:
  name: ixcloud-deployment
  labels:
    app: ixcloudapp
  #namespace: ixcloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ixcloudapp
  template:
    metadata:
      labels:
        app: ixcloudapp
    spec:
      containers:
      - image: ixkubernetesregistry.azurecr.io/ixdocker/ixcloud:latest
        name: ixcloudapp
        imagePullPolicy: Always
        command: ["/opt/intrexx/bin/linux/portal.sh"]
        args: ["/opt/intrexx/org/cloud"]
        resources:
          limits:
            cpu:  2
            memory: 2048Mi
          requests:
            cpu:    1
            memory:   1024Mi
        volumeMounts:
        - mountPath: /opt/intrexx/org/cloud
          name: ixcloudapp-volume
        - mountPath: /opt/intrexx/bin
          name: ixcloudapp-volume-bin
        - mountPath: /opt/intrexx/cfg
          name: ixcloudapp-volume-cfg
        - mountPath: /opt/intrexx/solr
          name: ixcloudapp-volume-solr          
      imagePullSecrets:
      - name: ixkubernetesregistry
      volumes:
      - name: ixcloudapp-volume
        nfs:
          server: 10.240.0.7
          path: /share/cloud
      - name: ixcloudapp-volume-bin
        nfs:
          server: 10.240.0.7
          path: /share/bin
      - name: ixcloudapp-volume-cfg
        nfs:
          server: 10.240.0.7
          path: /share/cfg
      - name: ixcloudapp-volume-solr
        nfs:
          server: 10.240.0.7
          path: /share/solr