apiVersion: apps/v1
kind: Deployment
metadata:
  name: ixcloud-manager-deployment
  labels:
    app: ixcloudmanager
  #namespace: ixcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ixcloudmanager
  template:
    metadata:
      labels:
        app: ixcloudmanager
    spec:
      containers:
      - image: ixkubernetesregistry.azurecr.io/ixdocker/ixcloud:latest
        name: ixcloud
        imagePullPolicy: Always
        command: ["/opt/intrexx/bin/linux/portal.sh"]
        args: ["/opt/intrexx/org/cloud"]
        resources:
          limits:
            cpu:  0.5
            memory: 2048Mi
          requests:
            cpu:    0.1
            memory: 512Mi
        volumeMounts:
        - mountPath: /opt/intrexx/org/cloud
          name: ixcloudapp-volume
        - mountPath: /opt/intrexx/bin
          name: ixcloudapp-volume-bin
        - mountPath: /opt/intrexx/cfg
          name: ixcloudapp-volume-cfg
      imagePullSecrets:
      - name: ixkubernetesregistry
      volumes:
        - name: ixcloudapp-volume
          nfs:
            server: 52.157.110.160
            path: /share/portal
        - name: ixcloudapp-volume-bin
          nfs:
            server: 52.157.110.160
            path: /share/bin
        - name: ixcloudapp-volume-cfg
          nfs:
            server: 52.157.110.160
            path: /share/cfg