kind: Service
apiVersion: v1
metadata:
  name: ixcloudsolrservice
#  namespace: ixcloud
spec:
  selector:
    app: ixcloudsolr
  type: NodePort
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983
#      nodePort: 8983