apiVersion: apps/v1
kind: Deployment
metadata:
  name: ixcloudsolr-deployment
  labels:
    app: ixcloudsolr
  #namespace: ixcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ixcloudsolr
  template:
    metadata:
      labels:
        app: ixcloudsolr
    spec:
      containers:
      - image: ixk8scr.azurecr.io/ixcloudsolr:latest
        name: ixcloudsolr
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1.0
            memory: 2048Mi
          requests:
            cpu: 0.1
            memory: 1024Mi
        volumeMounts:
        - mountPath: /opt/intrexx/org/cloud
          name: ixcloudapp-volume
        - mountPath: /opt/intrexx/bin
          name: ixcloudapp-volume-bin
        - mountPath: /opt/intrexx/cfg
          name: ixcloudapp-volume-cfg
        - mountPath: /opt/intrexx/solr
          name: ixcloudapp-volume-solr
      imagePullSecrets:
      - name: ixkubernetesregistry
      volumes:
      - name: ixcloudapp-volume
        nfs:
          server: 52.157.110.160
          path: /share/portal
      - name: ixcloudapp-volume-bin
        nfs:
          server: 52.157.110.160
          path: /share/bin
      - name: ixcloudapp-volume-cfg
        nfs:
          server: 52.157.110.160
          path: /share/cfg
      - name: ixcloudapp-volume-solr
        nfs:
          server: 52.157.110.160
          path: /share/solr