---
# This Playbook would deploy the postgresql server

- hosts: dbserver
  remote_user: "{{ ix_remote_user }}"
  become: yes
  vars_files:
    - ./vars.yml
  pre_tasks:
    - hostname: name="{{ hostname }}"
      when: ix_cloud_provider == "aws" or "vagrant"
  roles:
    - role: geerlingguy.postgresql
