version: '3'

services:
  db:
    image: "ixclouddb:latest"
    environment:
      - POSTGRES_PASSWORD:mysecretpassword
  solr:
    image: "ixcloudsolr:latest"
    volumes:
      - "/home/ubuntu/intrexx-cloud-playbooks/kubernetes/linux/share/cfg:/opt/intrexx/cfg"
      - "/home/ubuntu/intrexx-cloud-playbooks/kubernetes/linux/share/portal:/opt/intrexx/org/cloud"     
      - "/home/ubuntu/intrexx-cloud-playbooks/kubernetes//linux/share/solr:/opt/intrexx/solr"
  portal:
    image: "ixcloud:latest"
    command: /opt/intrexx/bin/linux/portal.sh /opt/intrexx/org/cloud
    ports:
      - "8080:1337"
      - "8443:8443"
      - "8101:8101"
    volumes:
      - "/home/ubuntu/intrexx-cloud-playbooks/kubernetes/linux/share/cfg:/opt/intrexx/cfg"
      - "/home/ubuntu/intrexx-cloud-playbooks/kubernetes/linux/share/portal:/opt/intrexx/org/cloud"
      - "/home/ubuntu/intrexx-cloud-playbooks/kubernetes/linux/share/solr:/opt/intrexx/solr"
      - "/tmp/ixstandalone:/var/log/intrexx"
    depends_on:
      - db
      - solr
    links:
      - db:ixclouddbservice
      - solr:ixcloudsolrservice
    deploy:
      mode: replicated
      replicas: 2  
volumes:
  files:
